# This file is automatically generated. Please do not modify.

from . import AsciiArt

parch = AsciiArt(match=r'''"parch"* | "Parch"* | "PARCH"*''', color='4 6', ascii=r"""
${c1}
                  +s;;:o-
              s/sssso+/-'+\
           +/ssssss/`
         /ssssssss/
       \ 'sssssss:
      `o+;ssssssso\
     /sssssssssssss\+
    ;ssssssssssssssss:
   :sssssssssssssssssso;
   /ssssssssssssssssssssss
  `+ssssssssssssssssssssso\
   so+'+ssssssssssssssss+'`
   '` +osssssoooooosssss++oo\
     /sssssssooooooosssssssso
    `osssssssssoooossssssssso:
      \sssssssssssssssssssss;
       `+osssssssssssssss:/'
         `\osssssssssso;+'
             `\+;so:+-`
""")
    